import os

import matplotlib.pyplot as plt
import pandas as pd


class ElutionCombinationProcessor:
    """
    Build and save valid RT-ordered metabolite combinations.

    This class supports both workflow modes:

    1. Without standards
       - `elution_orders` is a list of possible elution orders.

    2. With standards
       - `elution_orders` is a dictionary:
         {window_index: list_of_elution_orders}

    Parameters
    ----------
    elution_orders : list or dict
        Possible elution orders generated by ElutionOrderGenerator.
    elution_order_data : pandas.DataFrame
        Filtered mzDial data containing metabolite candidates.
    standards : pandas.DataFrame, optional
        Detected standards. Required only for standards-based workflow.
    output_dir : str
        Directory where Excel files and plots will be saved.
    """

    def __init__(
        self,
        elution_orders,
        elution_order_data,
        standards=None,
        output_dir="outputs/Elution_Results",
    ):
        self.elution_orders = elution_orders
        self.elution_order_data = elution_order_data
        self.standards = standards
        self.output_dir = output_dir

        os.makedirs(self.output_dir, exist_ok=True)

    def run(self):
        """
        Run combination generation.

        Automatically detects whether elution orders are:
        - a list: without standards
        - a dict: with standards/windows
        """
        if isinstance(self.elution_orders, dict):
            self._run_with_windows()
        else:
            self._run_without_windows()

    def build_combos(self, data, elution_order):
        """
        Generate valid combinations for one elution order.

        A valid combination must follow increasing observed RT:
        `Average Rt(min)` must increase along the selected metabolites.

        This preserves the original `used_start_rows` behavior from the
        previous implementations, preventing duplicated starting rows.

        Parameters
        ----------
        data : pandas.DataFrame
            Candidate rows for metabolites in the selected elution order.
        elution_order : list
            Ordered metabolite names.

        Returns
        -------
        list[pandas.DataFrame]
            Valid combinations sorted from longest to shortest.
        """
        valid_combos = []
        used_start_rows = set()

        def recurse(current_combo, current_rt_threshold, order_idx):
            if order_idx >= len(elution_order):
                if not current_combo.empty:
                    valid_combos.append(current_combo.reset_index(drop=True))
                return

            current_metabolite = elution_order[order_idx]
            metabolite_entries = data[data["Metabolite name"] == current_metabolite]

            added_any_row = False

            for idx, row in metabolite_entries.iterrows():
                if row["Average Rt(min)"] > current_rt_threshold:
                    if idx not in used_start_rows or not current_combo.empty:
                        new_combo = pd.concat(
                            [current_combo, row.to_frame().T],
                            ignore_index=True,
                        )

                        if current_combo.empty:
                            used_start_rows.add(idx)

                        recurse(
                            new_combo,
                            row["Average Rt(min)"],
                            order_idx + 1,
                        )
                        added_any_row = True

            # If no valid row is found for this metabolite, continue with
            # the next metabolite. This preserves partial valid combinations.
            if not added_any_row:
                recurse(current_combo, current_rt_threshold, order_idx + 1)

        recurse(pd.DataFrame(), -float("inf"), 0)

        return sorted(valid_combos, key=len, reverse=True)

    def _run_without_windows(self):
        """
        Process elution orders for the workflow without standards.
        """
        for order_idx, elution_order in enumerate(self.elution_orders, start=1):
            print(f"\nChecking Order {order_idx}/{len(self.elution_orders)}")

            data_subset = self._get_ordered_subset(elution_order)
            valid_combos = self.build_combos(data_subset, elution_order)

            if not valid_combos:
                print(f"No valid combinations found for Order {order_idx}")
                continue

            self._save_combinations(
                valid_combos=valid_combos,
                file_name=f"Valid_Combos_Order_{order_idx}.xlsx",
            )

            self._generate_longest_combo_plot(
                combo=valid_combos[0],
                plot_name=f"Longest_Valid_Combo_Order_{order_idx}.png",
                title=f"Longest Valid Combo - Order {order_idx}",
            )

    def _run_with_windows(self):
        """
        Process elution orders for the standards-based workflow.
        """
        for window_idx, order_list in self.elution_orders.items():
            print(f"\nProcessing Window {window_idx} - {len(order_list)} Elution Orders")

            for order_idx, elution_order in enumerate(order_list, start=1):
                print(f"Checking Window {window_idx}, Order {order_idx}")

                data_subset = self._get_ordered_subset(elution_order)
                valid_combos = self.build_combos(data_subset, elution_order)

                if not valid_combos:
                    print(
                        f"No valid combinations found for "
                        f"Window {window_idx}, Order {order_idx}"
                    )
                    continue

                self._save_combinations(
                    valid_combos=valid_combos,
                    file_name=f"Window_{window_idx}_Order_{order_idx}.xlsx",
                )

                self._generate_all_entries_plot(
                    data=data_subset,
                    plot_name=f"Window_{window_idx}_Order_{order_idx}_AllEntries.png",
                    title=(
                        f"All Possible Entries - "
                        f"Window {window_idx}, Order {order_idx}"
                    ),
                )

                if self._should_plot_longest_combo(data_subset):
                    self._generate_longest_combo_plot(
                        combo=valid_combos[0],
                        plot_name=f"Window_{window_idx}_Order_{order_idx}_LongestCombo.png",
                        title=(
                            f"Longest Combination - "
                            f"Window {window_idx}, Order {order_idx}"
                        ),
                    )
                else:
                    print(
                        f"Skipped longest combo plot for Window {window_idx}, "
                        f"Order {order_idx}: only standards are present."
                    )

    def _get_ordered_subset(self, elution_order):
        """
        Select candidate rows for an elution order and sort them accordingly.

        This replaces both previous approaches:
        - mapping metabolite name to order index
        - set_index(...).loc[...]

        It is safer because it keeps duplicate metabolite candidates.
        """
        data_subset = self.elution_order_data[
            self.elution_order_data["Metabolite name"].isin(elution_order)
        ].copy()

        order_lookup = {name: idx for idx, name in enumerate(elution_order)}
        data_subset["__order"] = data_subset["Metabolite name"].map(order_lookup)

        return (
            data_subset
            .sort_values("__order")
            .drop(columns="__order")
            .reset_index(drop=True)
        )

    def _save_combinations(self, valid_combos, file_name):
        """
        Save valid combinations to an Excel workbook.

        Each valid combination is saved in a separate sheet.
        Excel sheet names are limited to 31 characters.
        """
        output_path = os.path.join(self.output_dir, file_name)

        with pd.ExcelWriter(output_path, engine="xlsxwriter") as writer:
            for combo_idx, combo in enumerate(valid_combos, start=1):
                sheet_name = f"Combo_{combo_idx}"[:31]
                combo.to_excel(writer, sheet_name=sheet_name, index=False)

        print(f"Saved {len(valid_combos)} combinations to {output_path}")

    def _generate_all_entries_plot(self, data, plot_name, title):
        """
        Save a plot of Reference RT and Average RT for all candidate entries.

        This is used mainly in the standards workflow to inspect each RT window.
        """
        if data.empty:
            return

        plot_path = os.path.join(self.output_dir, plot_name)

        plt.figure(figsize=(8, 5))
        plt.scatter(
            data["Metabolite name"],
            data["Reference RT"],
            label="Reference RT",
            alpha=0.7,
        )
        plt.scatter(
            data["Metabolite name"],
            data["Average Rt(min)"],
            label="Average Rt(min)",
            alpha=0.7,
        )
        plt.xlabel("Metabolite Name")
        plt.ylabel("Retention Time (min)")
        plt.title(title)
        plt.xticks(rotation=45, ha="right")
        plt.legend()
        plt.tight_layout()
        plt.savefig(plot_path)
        plt.close()

        print(f"Saved plot: {plot_path}")

    def _generate_longest_combo_plot(self, combo, plot_name, title):
        """
        Save a plot for the longest valid combination.
        """
        if combo.empty:
            return

        plot_path = os.path.join(self.output_dir, plot_name)

        plt.figure(figsize=(8, 5))
        plt.plot(
            combo["Metabolite name"],
            combo["Reference RT"],
            marker="o",
            linestyle="-",
            label="Reference RT",
        )
        plt.plot(
            combo["Metabolite name"],
            combo["Average Rt(min)"],
            marker="s",
            linestyle="--",
            label="Average Rt(min)",
        )
        plt.xlabel("Metabolite Name")
        plt.ylabel("Retention Time (min)")
        plt.title(title)
        plt.xticks(rotation=45, ha="right")
        plt.legend()
        plt.tight_layout()
        plt.savefig(plot_path)
        plt.close()

        print(f"Saved plot: {plot_path}")

    def _should_plot_longest_combo(self, data):
        """
        Decide whether to plot the longest combo in standards mode.

        In the original standards workflow, the longest combo plot was skipped
        when the window contained only standards.
        """
        if self.standards is None or self.standards.empty:
            return True

        standard_rts = self.standards["Reference RT"].values
        non_standard_data = data[~data["Reference RT"].isin(standard_rts)]

        return not non_standard_data.empty